package lt.vu.usecases.mybatis.model;

public class ModelBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @param modelId the value for PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @param brandId the value for PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}