package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Factory;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    Factory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    List<Factory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int updateByPrimaryKey(Factory record);
}