package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.ModelBrand;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ModelBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int deleteByPrimaryKey(@Param("modelId") Integer modelId, @Param("brandId") Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int insert(ModelBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    List<ModelBrand> selectAll();
}